// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('OK', async function() {
    // Test name: OK
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | type | id=Nome completo | Maria Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Maria Teste")
    // 5 | type | id=E-mail | maria@gmail.com
    await driver.findElement(By.id("E-mail")).sendKeys("maria@gmail.com")
    // 6 | type | id=CEP | 74440-300
    await driver.findElement(By.id("CEP")).sendKeys("74440-300")
    // 7 | type | id=Telefone | (11) 95478-2356
    await driver.findElement(By.id("Telefone")).sendKeys("(11) 95478-2356")
    // 8 | type | id=CPF | 241.268.540-10
    await driver.findElement(By.id("CPF")).sendKeys("241.268.540-10")
    // 9 | click | id=Termos | 
    await driver.findElement(By.id("Termos")).click()
    // 10 | click | css=.d-flex | 
    await driver.findElement(By.css(".d-flex")).click()
    // 11 | close |  | 
    await driver.close()
  })
  it('SEM CPF', async function() {
    // Test name: SEM CPF
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | type | id=Nome completo | Joao Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Joao Teste")
    // 5 | type | id=E-mail | joao@gmail.com
    await driver.findElement(By.id("E-mail")).sendKeys("joao@gmail.com")
    // 6 | type | id=CEP | 13183-382
    await driver.findElement(By.id("CEP")).sendKeys("13183-382")
    // 7 | type | id=Telefone | (11) 95682-3525
    await driver.findElement(By.id("Telefone")).sendKeys("(11) 95682-3525")
    // 8 | click | id=Termos | 
    await driver.findElement(By.id("Termos")).click()
    // 9 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 10 | close |  | 
    await driver.close()
  })
  it('SEM_CEP', async function() {
    // Test name: SEM_CEP
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | type | id=Nome completo | Nome Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Nome Teste")
    // 5 | type | id=E-mail | nome@hotmail.com
    await driver.findElement(By.id("E-mail")).sendKeys("nome@hotmail.com")
    // 6 | type | id=Telefone | (11) 98552-3569
    await driver.findElement(By.id("Telefone")).sendKeys("(11) 98552-3569")
    // 7 | type | id=CPF | 241.268.540-10
    await driver.findElement(By.id("CPF")).sendKeys("241.268.540-10")
    // 8 | click | id=Termos | 
    await driver.findElement(By.id("Termos")).click()
    // 9 | click | css=.d-flex | 
    await driver.findElement(By.css(".d-flex")).click()
    // 10 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 11 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | mouseOut | css=.btn | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 13 | assertText | css=.col-lg-6:nth-child(3) .invalid-feedback | Campo obrigatório
    assert(await driver.findElement(By.css(".col-lg-6:nth-child(3) .invalid-feedback")).getText() == "Campo obrigatório")
    // 14 | close |  | 
    await driver.close()
  })
  it('E_Mail Invalido', async function() {
    // Test name: E_Mail Invalido
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | click | id=Nome completo | 
    await driver.findElement(By.id("Nome completo")).click()
    // 5 | click | id=Nome completo | 
    await driver.findElement(By.id("Nome completo")).click()
    // 6 | type | id=Nome completo | Maria Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Maria Teste")
    // 7 | type | id=E-mail | maria@gmail
    await driver.findElement(By.id("E-mail")).sendKeys("maria@gmail")
    // 8 | type | id=CEP | 74440-300
    await driver.findElement(By.id("CEP")).sendKeys("74440-300")
    // 9 | assertText | css=.col-lg-6:nth-child(2) .invalid-feedback | E-mail inválido
    assert(await driver.findElement(By.css(".col-lg-6:nth-child(2) .invalid-feedback")).getText() == "E-mail inválido")
    // 10 | close |  | 
    await driver.close()
  })
  it('CEP_Invalido', async function() {
    // Test name: CEP_Invalido
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | type | id=Nome completo | Nome Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Nome Teste")
    // 5 | type | id=E-mail | nome@hotmail.com
    await driver.findElement(By.id("E-mail")).sendKeys("nome@hotmail.com")
    // 6 | type | id=CEP | 74440-000
    await driver.findElement(By.id("CEP")).sendKeys("74440-000")
    // 7 | type | id=Telefone | (11) 98552-3569
    await driver.findElement(By.id("Telefone")).sendKeys("(11) 98552-3569")
    // 8 | assertText | css=.col-lg-6:nth-child(3) .invalid-feedback | CEP inválido
    assert(await driver.findElement(By.css(".col-lg-6:nth-child(3) .invalid-feedback")).getText() == "CEP inválido")
    // 9 | close |  | 
    await driver.close()
  })
  it('Telefone_Invalido', async function() {
    // Test name: Telefone_Invalido
    // Step # | name | target | value
    // 1 | open | https://www.cartaodetodos.com.br/calculadora/ | 
    await driver.get("https://www.cartaodetodos.com.br/calculadora/")
    // 2 | setWindowSize | 1366x720 | 
    await driver.manage().window().setRect({ width: 1366, height: 720 })
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | type | id=Nome completo | Maria Teste
    await driver.findElement(By.id("Nome completo")).sendKeys("Maria Teste")
    // 5 | type | id=E-mail | maria@gmail.com
    await driver.findElement(By.id("E-mail")).sendKeys("maria@gmail.com")
    // 6 | type | id=CEP | 74440-300
    await driver.findElement(By.id("CEP")).sendKeys("74440-300")
    // 7 | type | id=Telefone | (11) 95478-23
    await driver.findElement(By.id("Telefone")).sendKeys("(11) 95478-23")
    // 8 | type | id=CPF | 241.268.540-10
    await driver.findElement(By.id("CPF")).sendKeys("241.268.540-10")
    // 9 | assertText | css=.col-lg-6:nth-child(4) .invalid-feedback | Telefone inválido
    assert(await driver.findElement(By.css(".col-lg-6:nth-child(4) .invalid-feedback")).getText() == "Telefone inválido")
    // 10 | close |  | 
    await driver.close()
  })
})
